---
- name: basic packages
  hosts: local
  become: yes
  tasks:
    - community.general.pacman:
        name:
          - dnsutils
          - libheif
          - libvips
          - nmap
          - postfix
          - postgresql
          - ripgrep
          - tmux
        state: present
        update_cache: yes
